@startuml
title 「カートに入れる」

actor User



rectangle SESSION {
  entity カート情報
}


rectangle RDB {
  entity 商品
}

rectangle ショップシステム {
  boundary 商品画面
  control 商品情報を取得
  control カート更新
  control カート表示
  boundary カート画面
}

User - 商品画面
商品画面 --> 商品情報を取得: カートに入れるボタン押下
商品情報を取得 - 商品
商品情報を取得 --> カート更新: "[みつかった]"
商品情報を取得 ---> カート表示: "[みつからない]"
カート更新 -> カート表示
カート表示 -> カート画面
カート更新 - カート情報: 検索/更新

left footer
  カートに入れるAPI

  ユースケース名：AddItemToCart
  概要：ユーザが商品をカートに入れる
  アクタ：ユーザ
  事前条件：必要な商品が登録されていること
  トリガ：
  基本フロー：
    1. POSTリクエストから商品IDと商品個数を取得
    2. DBから商品IDで商品を取得
    3. カートに商品を入れる
    4. カートをセッションに保存
    5. レスポンスを返す
  備考：

end footer

@enduml